apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: $(MODEL_NAME)
spec:
  mpiReplicaSpecs:
    Launcher:
      template:
        spec:
          containers:
          - name: mpi-launcher
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-large-fp32-training
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            envFrom:
            - configMapRef:
                name: mlops-env
            command:
            - $(MODEL_DIR)/examples/fp32_training_multi_node.sh
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: $(NFS_MOUNT_PATH)
    Worker:
      template:
        spec:
          containers:
          - name: mpi-worker
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-large-fp32-training
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            envFrom:
            - configMapRef:
                name: mlops-env
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: $(NFS_MOUNT_PATH)
