apiVersion: v1
kind: Pod
metadata:
  name: resnet50v1-5-fp32-training # {"$openapi":"MODEL_NAME"}
spec:
  serviceAccountName: resnet50v1-5-fp32-training # {"$openapi":"MODEL_NAME"}
  securityContext:
    runAsUser: 0 # {"$openapi":"USER_ID"}
    runAsGroup: 0 # {"$openapi":"GROUP_ID"}
    fsGroup: 0 # {"$openapi":"FS_ID"}
  containers:
  - name: single-node
    image: docker.io/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training # {"$openapi":"IMAGE"}
    workingDir: /workspace/resnet50v1-5-fp32-training # {"$openapi":"MODEL_DIR"}
    command: # {"$openapi":"COMMAND"}
    - /workspace/resnet50v1-5-fp32-training/quickstart/fp32_training_demo.sh # {"$openapi":"COMMAND"}
    env:
    - name: DATASET_DIR
      value: /datasets # {"$openapi":"DATASET_DIR"}
    - name: GROUP_ID
      value: "0" # {"$openapi":"GROUP_ID_VALUE"}
    - name: GROUP_NAME
      value: root # {"$openapi":"GROUP_NAME"}
    - name: OUTPUT_DIR
      value: /nfs/root/resnet50v1-5-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
    - name: USER_ID
      value: "0" # {"$openapi":"USER_ID_VALUE"}
    - name: USER_NAME
      value: root # {"$openapi":"USER_NAME"}
    volumeMounts:
    - name: datasets
      mountPath: /datasets # {"$openapi":"DATASET_DIR"}
      readOnly: true
    - name: nfs-path
      mountPath: /nfs # {"$openapi":"NFS_PATH"}
    - name: mlops-scripts
      mountPath: /workspace/resnet50v1-5-fp32-training/quickstart/fp32_training_demo.sh # {"$openapi":"COMMAND"}
      subPath: fp32_training_demo.sh # {"$openapi":"MODEL_SCRIPT"}
  volumes:
  - name: datasets
    hostPath:
      path: /datasets # {"$openapi":"DATASET_DIR"}
  - name: nfs-path
    nfs:
      server: 0.0.0.0 # {"$openapi":"NFS_SERVER"}
      path: /nfs # {"$openapi":"NFS_PATH"}
  - name: mlops-scripts
    configMap:
      name: mlops-scripts
      defaultMode: 0770
      items:
      - key: fp32_training_demo.sh # {"$openapi":"MODEL_SCRIPT"}
        path: fp32_training_demo.sh # {"$openapi":"MODEL_SCRIPT"}
  restartPolicy: OnFailure
