apiVersion: v1
kind: Pod
metadata:
  name: $(MODEL_NAME)
spec:
  securityContext:
    runAsUser: $(USER_ID)
    runAsGroup: $(GROUP_ID)
    fsGroup: $(GROUP_ID)
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-$(MODEL_NAME)
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mlops-env
    workingDir: $(MODEL_DIR)
    command:
    - $(MODEL_DIR)/quickstart/$(MODEL_SCRIPT)
    volumeMounts:
    - name: datasets
      mountPath: $(DATASET_DIR)
      readOnly: true
    - name: users
      mountPath: $(NFS_MOUNT_PATH)
