apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- train_and_serve.yaml
configMapGenerator:
- files:
  - fp32_training_check_accuracy.sh
  name: mlops-scripts-wide-deep-large-ds-fp32-training
generatorOptions:
  disableNameSuffixHash: true
namespace: default
