varReference:
- kind: MPIJob
  path: metadata/name
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Launcher/template/spec/containers/image
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Launcher/template/spec/containers/command
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Launcher/template/spec/containers/volumeMounts/mountPath
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Worker/template/spec/containers/image
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Worker/template/spec/containers/command
- kind: MPIJob
  path: spec/mpiReplicaSpecs/Worker/template/spec/containers/volumeMounts/mountPath
