apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: $(DATASET_DIR)
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
  labels:
    storage-class: users-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 6Gi
  nfs:
    server: $(NFS_SERVER)
    path: $(NFS_PATH)
