apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      storage-class: users-nfs
