apiVersion: kustomize.config.k8s.io/v1beta1
kind:
bases:
- ../../../common/tensorflow/k8s/mlops/base
configMapGenerator:
- name: mlops-env
  env: mlops.env
  behavior: merge
generatorOptions:
  disableNameSuffixHash: true
resources:
- train_and_serve.yaml
configurations:
- mlops.yaml
vars:
- name: DATASET_DIR
  fieldref:
    fieldPath: data.DATASET_DIR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: OUTPUT_DIR
  fieldref:
    fieldPath: data.OUTPUT_DIR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: GROUP_ID
  fieldref:
    fieldPath: data.GROUP_ID
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: MODEL_NAME
  fieldref:
    fieldPath: data.MODEL_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: NFS_MOUNT_PATH
  fieldref:
    fieldPath: data.NFS_MOUNT_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: WORKFLOW_NAME
  fieldref:
    fieldPath: data.WORKFLOW_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: REPLICAS
  fieldref:
    fieldPath: data.REPLICAS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: TF_SERVING_PORT
  fieldref:
    fieldPath: data.TF_SERVING_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: MODEL_DIR
  fieldref:
    fieldPath: data.MODEL_DIR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: MODEL_SCRIPT
  fieldref:
    fieldPath: data.MODEL_SCRIPT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: REGISTRY
  fieldref:
    fieldPath: data.REGISTRY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: USER_ID
  fieldref:
    fieldPath: data.USER_ID
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
- name: RETRY_LIMIT
  fieldref:
    fieldPath: data.RETRY_LIMIT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mlops-env
