apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: $(MODEL_NAME)
spec:
  mpiReplicaSpecs:
    Launcher:
      template:
        spec:
          containers:
          - name: mpi-launcher
            imagePullPolicy: Always
            workingDir: $(MODEL_DIR)
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-$(MODEL_NAME)
            securityContext:
              runAsUser: $(USER_ID)
              runAsGroup: $(GROUP_ID)
              fsGroup: $(GROUP_ID)
            envFrom:
            - configMapRef:
                name: mlops-env
            command:
            - $(MODEL_DIR)/examples/$(MODEL_SCRIPT)
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: $(NFS_MOUNT_PATH)
    Worker:
      template:
        spec:
          containers:
          - name: mpi-worker
            imagePullPolicy: Always
            workingDir: $(MODEL_DIR)
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-$(MODEL_NAME)
            securityContext:
              runAsUser: $(USER_ID)
              runAsGroup: $(GROUP_ID)
              fsGroup: $(GROUP_ID)
            envFrom:
            - configMapRef:
                name: mlops-env
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: $(NFS_MOUNT_PATH)
