releases:
  dockerfiles:
    tag_specs:
    - '{ubuntu}{intel-python}{modin-ray}{scikit-learn}{scikit-learn-census}'
  ml:
    tag_specs:
    - '{ubuntu}{intel-python}{modin-ray}{scikit-learn}{scikit-learn-census}'
slice_sets:
  modin-ray:
  - add_to_name: ""
    partials:
    - gcc-8
    - ml/modin-ray
  scikit-learn-census:
  - add_to_name: -census
    args:
    - UBUNTU_VERSION=20.04
    - PACKAGE_NAME=scikit-learn-census
    dockerfile_subdirectory: ml/scikit-learn
    partials:
    - model_package
    - ml/test-scikit-learn
    files:
    - source:  dockerfiles/ml/scikit-learn/censue_modin.py
      destination: censue_monin.py
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/datasets/ipums_education2income_1970-2010.csv.gz
      destination: ipums_education2income_1970-2010.csv.gz
