apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: bert-large-fp32-training # {"$openapi":"MODEL_NAME"}
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          serviceAccountName: bert-large-fp32-training # {"$openapi":"MODEL_NAME"}
          containers:
          - name: mpi-launcher
            imagePullPolicy: Always
            workingDir: /workspace/bert-large-fp32-training # {"$openapi":"MODEL_DIR"}
            image: docker.io/intel/language-modeling:tf-2.3.0-imz-2.0.0-bert-large-fp32-training # {"$openapi":"IMAGE"}
            securityContext:
              runAsUser: 0 # {"$openapi":"USER_ID"}
              runAsGroup: 0 # {"$openapi":"GROUP_ID"}
              fsGroup: 0 # {"$openapi":"FS_ID"}
            env:
            - name: MODEL_DIR
              value: /workspace/bert-large-fp32-training # {"$openapi":"MODEL_DIR"} 
            - name: DATASET_DIR
              value: /datasets # {"$openapi":"DATASET_DIR"}
            - name: GLUE_DIR
              value: bert_official # {"$openapi":"GLUE_DIR"}
            - name: BERT_BASE_DIR
              value: bert_official/MRPC # {"$openapi":"BERT_BASE_DIR"}
            - name: CHECKPOINT_DIR
              value: /checkpoints # {"$openapi":"CHECKPOINT_DIR"}
            - name: GROUP_ID
              value: "0" # {"$openapi":"GROUP_ID_VALUE"}
            - name: GROUP_NAME
              value: root # {"$openapi":"GROUP_NAME"}
            - name: OUTPUT_DIR
              value: /nfs/root/bert-large-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
            - name: USER_ID
              value: "0" # {"$openapi":"USER_ID_VALUE"}
            - name: USER_NAME
              value: root # {"$openapi":"USER_NAME"}
            - name: PYTHONPATH
              value: /workspace/bert-large-fp32-training/models/language_modeling/tensorflow/bert_large/training:$PYTHONPATH # {"$openapi":"PYTHONPATH"}
            - name: LD_LIBRARY_PATH
              value: /usr/local/lib:/usr/local/lib/mpirun:$LD_LIBRARY_PATH
            command:
            - mpirun
            args:
            - --allow-run-as-root
            - -np
            - "2"
            - -x
            - PYTHONPATH
            - -x
            - LD_LIBRARY_PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - -mca
            - btl_tcp_if_exclude
            - lo,docker0
            - -bind-to
            - none
            - -map-by
            - slot
            - python3
            - /workspace/bert-large-fp32-training/models/language_modeling/tensorflow/bert_large/training/fp32/run_classifier.py # {"$openapi":"MODEL_SCRIPT"}
            - --task_name=MRPC
            - --do_train=true
            - --do_eval=true
            - --data_dir=$(DATASET_DIR)/$(GLUE_DIR)/MRPC
            - --vocab_file=$(DATASET_DIR)/$(BERT_BASE_DIR)/uncased_L-12_H-768_A-12/vocab.txt
            - --bert_config_file=$(DATASET_DIR)/$(BERT_BASE_DIR)/uncased_L-12_H-768_A-12/bert_config.json
            - --init_checkpoint=$(DATASET_DIR)/$(BERT_BASE_DIR)/uncased_L-12_H-768_A-12/bert_model.ckpt
            - --max_seq_length=128
            - --train_batch_size=32
            - --learning_rate=2e-5
            - --num_train_epochs=3.0
            - --output_dir=$(OUTPUT_DIR)
            - --use_tpu=False
            - --precision=fp32
            - --do_lower_case=True
            volumeMounts:
            - name: datasets
              mountPath: /datasets # {"$openapi":"DATASET_DIR"}
              readOnly: true
            - name: nfs-path
              mountPath: /nfs # {"$openapi":"NFS_PATH"}
          volumes:
          - name: datasets
            hostPath:
              path: /datasets # {"$openapi":"DATASET_DIR"}
          - name: nfs-path
            nfs:
              server: 0.0.0.0 # {"$openapi":"NFS_SERVER"}
              path: /nfs # {"$openapi":"NFS_PATH"}
    Worker:
      replicas: 2 # {"$openapi":"WORKERS"}
      template:
        spec:
          serviceAccountName: bert-large-fp32-training # {"$openapi":"MODEL_NAME"}
          containers:
          - name: mpi-worker
            imagePullPolicy: Always
            workingDir: /workspace/bert-large-fp32-training # {"$openapi":"MODEL_DIR"}
            image: docker.io/intel/language-modeling:tf-2.3.0-imz-2.0.0-bert-large-fp32-training # {"$openapi":"IMAGE"}
            securityContext:
              runAsUser: 0 # {"$openapi":"USER_ID"}
              runAsGroup: 0 # {"$openapi":"GROUP_ID"}
              fsGroup: 0 # {"$openapi":"FS_ID"}
            env:
            - name: MODEL_DIR
              value: /workspace/bert-large-fp32-training # {"$openapi":"MODEL_DIR"} 
            - name: DATASET_DIR
              value: /datasets # {"$openapi":"DATASET_DIR"}
            - name: GROUP_ID
              value: "0" # {"$openapi":"GROUP_ID_VALUE"}
            - name: GROUP_NAME
              value: root # {"$openapi":"GROUP_NAME"}
            - name: OUTPUT_DIR
              value: /nfs/root/bert-large-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
            - name: USER_ID
              value: "0" # {"$openapi":"USER_ID_VALUE"}
            - name: USER_NAME
              value: root # {"$openapi":"USER_NAME"}
            volumeMounts:
            - name: datasets
              mountPath: /datasets # {"$openapi":"DATASET_DIR"}
              readOnly: true
            - name: nfs-path
              mountPath: /nfs # {"$openapi":"NFS_PATH"}
          volumes:
          - name: datasets
            hostPath:
              path: /datasets # {"$openapi":"DATASET_DIR"}
          - name: nfs-path
            nfs:
              server: 0.0.0.0 # {"$openapi":"NFS_SERVER"}
              path: /nfs # {"$openapi":"NFS_PATH"}
