apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- single_node_accuracy.yaml
configMapGenerator:
- files:
  - fp32_accuracy.sh
  - preprocess_coco_val.sh
  name: mlops-scripts-rfcn-fp32-inference
generatorOptions:
  disableNameSuffixHash: true
namespace: default
