apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: $(WORKFLOW_NAME)
spec:
  entrypoint: $(MODEL_NAME)
  volumeClaimTemplates:
  - metadata:
      name: rfcn-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 6Gi
      storageClassName: local-path
  templates:
  - name: $(MODEL_NAME)
    steps:
    - - name: preprocess-coco
        template: preprocess-coco
    - - name: rfcn-fp32-accuracy
        template: rfcn-fp32-accuracy
    securityContext:
      runAsUser: $(USER_ID)
      runAsGroup: $(GROUP_ID)
      fsGroup: $(GROUP_ID)
  - name: preprocess-coco
    container:
      image: $(REGISTRY)/model-zoo:1.15.2-object-detection-preprocess-coco-val
      command: ["/workspace/preprocess-coco-val/scripts/preprocess_coco_val.sh"]
      envFrom:
       - configMapRef:
           name: mlops-env
      env:
      - name: VAL_IMAGE_DIR
        value: $(DATASET_DIR)/val2017
      - name: ANNOTATIONS_DIR
        value: $(DATASET_DIR)/annotations
      - name: OUTPUT_DIR
        value: /mnt/vol/tf_records
      volumeMounts:
      - name: rfcn-pvc
        mountPath: /mnt/vol
      - name: coco-raw-data
        mountPath: $(DATASET_DIR)
        readOnly: true
    volumes:
      - name: coco-raw-data
        hostPath:
          path: $(DATASET_DIR)
  - name: rfcn-fp32-accuracy
    container:
      image: $(REGISTRY)/model-zoo:2.1.0-object-detection-$(MODEL_NAME)
      command: [$(MODEL_DIR)/quickstart/fp32_accuracy.sh]
      envFrom:
      - configMapRef:
          name: mlops-env
      env:
      - name: VAL_IMAGE_DIR
        value: /dataset/raw_images
      - name: DATASET_DIR
        value: /mnt/vol/tf_records
      - name: OUTPUT_DIR
        value: /mnt/vol
      volumeMounts:
      - name: rfcn-pvc
        mountPath: /mnt/vol
