apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: rfcn-fp32-inference-wf # {"$openapi":"WORKFLOW_NAME"}
spec:
  entrypoint: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
  templates:
  - name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
    steps:
    - - name: preprocess-coco
        template: preprocess-coco
    - - name: rfcn-fp32-accuracy
        template: rfcn-fp32-accuracy
  - name: preprocess-coco
    securityContext:
      runAsUser: 0 # {"$openapi":"USER_ID"}
      runAsGroup: 0 # {"$openapi":"GROUP_ID"}
      fsGroup: 0 # {"$openapi":"FS_ID"}
    container:
      image: docker.io/model-zoo:1.15.2-object-detection-preprocess-coco-val # {"$openapi":"PREPROCESS_IMAGE"}
      command: # {"$openapi":"PREPROCESS_COMMAND"}
      - /workspace/preprocess-coco-val/scripts/preprocess_coco_val.sh # {"$openapi":"PREPROCESS_COMMAND"}
      env:
      - name: VAL_IMAGE_DIR
        value: /datasets/val2017 # {"$openapi":"VAL_IMAGE_DIR"}
      - name: ANNOTATIONS_DIR
        value: /datasets/annotations # {"$openapi":"ANNOTATIONS_DIR"}
      - name: OUTPUT_DIR
        value: /nfs/root/rfcn-fp32-inference/output # {"$openapi":"OUTPUT_PATH"}
      - name: GROUP_ID
        value: "0" # {"$openapi":"GROUP_ID_VALUE"}
      - name: GROUP_NAME
        value: root # {"$openapi":"GROUP_NAME"}
      - name: USER_ID
        value: "0" # {"$openapi":"USER_ID_VALUE"}
      - name: USER_NAME
        value: root # {"$openapi":"USER_NAME"}
      volumeMounts:
      - name: nfs-path
        mountPath: /nfs # {"$openapi":"NFS_PATH"}
      - name: coco-raw-data
        mountPath: /datasets # {"$openapi":"DATASET_DIR"}
        readOnly: true
      - name: mlops-scripts
        mountPath: /workspace/preprocess-coco-val/scripts/preprocess_coco_val.sh # {"$openapi":"PREPROCESS_COMMAND"}
        subPath: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
    volumes:
    - name: coco-raw-data
      hostPath:
        path: /datasets # {"$openapi":"DATASET_DIR"}
    - name: nfs-path
      nfs:
        server: 0.0.0.0 # {"$openapi":"NFS_SERVER"}
        path: /nfs # {"$openapi":"NFS_PATH"}
    - name: mlops-scripts
      configMap:
        name: mlops-scripts-rfcn-fp32-inference # {"$openapi":"MODEL_CONFIGMAP_NAME"}
        defaultMode: 0770
        items:
        - key: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
          path: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
  - name: rfcn-fp32-accuracy
    securityContext:
      runAsUser: 0 # {"$openapi":"USER_ID"}
      runAsGroup: 0 # {"$openapi":"GROUP_ID"}
      fsGroup: 0 # {"$openapi":"FS_ID"}
    container:
      image: docker.io/model-zoo:2.1.0-object-detection-rfcn-fp32-inference # {"$openapi":"IMAGE"}
      imagePullPolicy: Always
      command: # {"$openapi":"MODEL_COMMAND"}
      - /workspace/rfcn-fp32-inference/quickstart/fp32_accuracy.sh # {"$openapi":"MODEL_COMMAND"}
      env:
      - name: MODELS_DIR
        value: /workspace/rfcn-fp32-inference # {"$openapi":"MODELS_DIR"}
      - name: VAL_IMAGE_DIR
        value: /datasets/val2017 # {"$openapi":"VAL_IMAGE_DIR"}
      - name: DATASET_DIR
        value: /nfs/root/rfcn-fp32-inference/output # {"$openapi":"OUTPUT_PATH"}
      - name: OUTPUT_DIR
        value: /nfs/root/rfcn-fp32-inference/output # {"$openapi":"OUTPUT_PATH"}
      - name: GROUP_ID
        value: "0" # {"$openapi":"GROUP_ID_VALUE"}
      - name: GROUP_NAME
        value: root # {"$openapi":"GROUP_NAME"}
      - name: USER_ID
        value: "0" # {"$openapi":"USER_ID_VALUE"}
      - name: USER_NAME
        value: root # {"$openapi":"USER_NAME"}
      volumeMounts:
      - name: nfs-path
        mountPath: /nfs # {"$openapi":"NFS_PATH"}
      - name: mlops-scripts
        mountPath: /workspace/rfcn-fp32-inference/quickstart/fp32_accuracy.sh # {"$openapi":"MODEL_COMMAND"}
        subPath: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
    volumes:
    - name: nfs-path
      nfs:
        server: 0.0.0.0 # {"$openapi":"NFS_SERVER"}
        path: /nfs # {"$openapi":"NFS_PATH"}
    - name: mlops-scripts
      configMap:
        name: mlops-scripts-rfcn-fp32-inference # {"$openapi":"MODEL_CONFIGMAP_NAME"}
        defaultMode: 0770
        items:
        - key: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
          path: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
