apiVersion: v1
kind: Pod
metadata:
  name: $(MODEL_NAME)
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mlops-env
    workingDir: /
    command:
    - $(MODEL_DIR)/examples/fp32_training_demo.sh
    volumeMounts:
    - name: datasets
      mountPath: $(DATASET_DIR)
      readOnly: true
    - name: users
      mountPath: $(NFS_MOUNT_PATH)
