releases:
  versioned:
    tag_specs:
    - '{tensorflow-spr}'
slice_sets:
  tensorflow-spr:
    - add_to_name: tensorflow-spr
      dockerfile_subdirectory: spr_ww22_containers
      args:
        - TENSORFLOW_WHEEL=tf_nightly-2.6.0-cp36-cp36m-linux_x86_64.whl
        - PACKAGE_NAME=tensorflow-spr
      partials:
        - centos8.3.2011-base
        - tensorflow/spr-dnnl-max-var
        - tensorflow/tf-installs
      files:
        - source: quickstart/spr_base/tensorflow/build.sh
          destination: build.sh
        - source: dockerfiles/spr_ww22_containers/tensorflow-spr.Dockerfile
          destination: tensorflow-spr.Dockerfile
        - source: tools/docker/whls
          destination: whls
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/spr_base/tensorflow/README.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/spr_base/tensorflow/.docs/title.md
          - name: Description
            uri: models/quickstart/spr_base/tensorflow/.docs/description.md
          - name: Model Package
            uri: models/quickstart/spr_base/tensorflow/.docs/container_package.md
          - name: Docker
            uri: models/quickstart/spr_base/tensorflow/.docs/docker.md
          - name: License
            uri: models/quickstart/spr_base/tensorflow/.docs/license.md
          name: README.md
          text_replace:
            <package name>: tensorflow-spr.tar.gz
            <package dir>: tensorflow-spr
            <docker image>: tensorflow-ww22-spr:243fa30a-centos-8
          uri: models/quickstart/spr_base/tensorflow
