apiVersion: v1
kind: Pod
metadata:
  name: $(MODEL_NAME)
spec:
  serviceAccountName: model-service
  containers:
  - name: single-node
    imagePullPolicy: Always
  volumes:
  - name: users
    persistentVolumeClaim:
      claimName: users-pvc
  - name: datasets
    persistentVolumeClaim:
      claimName: datasets-pvc
